/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas;

import javax.swing.*;
import java.awt.*;
import java.io.*;
import java.util.*;
import java.lang.*;
import java.text.SimpleDateFormat;

/**
 *
 * @author ACER
 */
public class UASSSS extends javax.swing.JFrame {

    String timeStamp = new SimpleDateFormat("yyyy-MM-dd_HH.mm.ss").format(Calendar.getInstance().getTime());
    String[][][] kr = new String[6][10][4];
    int[] x = new int[6];
    int total = 0, hp;
    int hs = 0;
    int totalSemua;
    int mejaSemua;

    /**
     * Creates new form UASSSS
     */
    public UASSSS() {
        initComponents();
        PesanMakanan.addItem("Tahu Goreng");
        PesanMakanan.addItem("Kentang Goreng");
        PesanMakanan.addItem("Roti Bakar");
        PesanMinuman.addItem("Jus Mangga");
        PesanMinuman.addItem("Jus Jambu");
        PesanMinuman.addItem("Jus Alpukat");
        PesanMinuman.addItem("Red Velvet");
        PesanMinuman.addItem("Charcoal");
        PesanMinuman.addItem("Chapuchino");
        PesanMinuman.addItem("Americano");
        PesanMinuman.addItem("Arabica");
        Makanan.addItem("Nasi Goreng");
        Makanan.addItem("Mie Goreng");
        Makanan.addItem("Crispy Chiken");
        Makanan.addItem("Hamburger");
        Makanan.addItem("Pasta");
        Meja.addItem("Meja 01");
        Meja.addItem("Meja 02");
        Meja.addItem("Meja 03");
        Meja.addItem("Meja 04");
        Meja.addItem("Meja 05");
        Meja.addItem("Meja 06");

        if (aplikasii.isVisible()) {
            aplikasii.setVisible(false);
        }

        if (historyy.isVisible()) {
            historyy.setVisible(false);
        }
        if (logoutt.isVisible()) {
            logoutt.setVisible(false);
        }
        x[0] = 0;
        x[1] = 0;
        x[2] = 0;
        x[3] = 0;
        x[4] = 0;
        x[5] = 0;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        utama = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        BtnLogin = new javax.swing.JButton();
        payment01 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        tbl1 = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        TotalHarga = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        Bayar = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        Kembalian = new javax.swing.JTextField();
        btnKembalian = new javax.swing.JButton();
        back2 = new javax.swing.JButton();
        Meja1 = new javax.swing.JTextField();
        Close3 = new javax.swing.JButton();
        login = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        login1 = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        history = new javax.swing.JPanel();
        totalSeluruh = new javax.swing.JTextField();
        jScrollPane12 = new javax.swing.JScrollPane();
        tbl2 = new javax.swing.JTable();
        Reset = new javax.swing.JButton();
        Close1 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        aplikasi = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        PesanMakanan = new javax.swing.JComboBox<>();
        meja04 = new javax.swing.JButton();
        meja03 = new javax.swing.JButton();
        meja02 = new javax.swing.JButton();
        meja01 = new javax.swing.JButton();
        Meja = new javax.swing.JComboBox<>();
        jScrollPane10 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        JumlahMakanan = new javax.swing.JTextField();
        JumlahMinuman = new javax.swing.JTextField();
        PesanMinuman = new javax.swing.JComboBox<>();
        TambahMinuman = new javax.swing.JButton();
        TambahMakanan = new javax.swing.JButton();
        btnMakan = new javax.swing.JButton();
        jmlMakan = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        Makanan = new javax.swing.JComboBox<>();
        meja06 = new javax.swing.JButton();
        meja05 = new javax.swing.JButton();
        Reset1 = new javax.swing.JButton();
        Close2 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        help = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        about = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        aboutt = new javax.swing.JMenuItem();
        helpp = new javax.swing.JMenuItem();
        loginn = new javax.swing.JMenuItem();
        logoutt = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        aplikasii = new javax.swing.JMenuItem();
        historyy = new javax.swing.JMenuItem();

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 45)); // NOI18N
        jLabel5.setText("ANGGOTA KELOMPOK");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Sitka Text", 0, 24)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("M. Ainurrofiq Anwar Buhang\n21051204052\n\nFajar Hindi Saputra\n21051204050\n\nAzhar Daryl Ravysa\n21051204038");
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Back");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 45)); // NOI18N
        jLabel6.setText("ANGGOTA KELOMPOK");

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Sitka Text", 0, 24)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("M. Ainurrofiq Anwar Buhang\n21051204052\n\nFajar Hindi Saputra\n21051204050\n\nAzhar Daryl Ravysa\n21051204038");
        jScrollPane2.setViewportView(jTextArea2);

        jButton2.setText("Back");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CAFE.IN");
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Universitas Negeri Surabaya");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uas/UNESA.png"))); // NOI18N
        jLabel12.setToolTipText("");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uas/UNESA.png"))); // NOI18N
        jLabel13.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        utama.setLayout(new java.awt.CardLayout());

        home.setBackground(new java.awt.Color(0, 153, 153));
        home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uas/Icon 0.png"))); // NOI18N
        home.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 13, 455, 476));

        BtnLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnLogin.setText("LOGIN");
        BtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoginActionPerformed(evt);
            }
        });
        home.add(BtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 519, -1, -1));

        utama.add(home, "card2");

        payment01.setBackground(new java.awt.Color(0, 153, 153));
        payment01.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Nomor Meja");
        payment01.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Daftar Pesanan", "Harga", "Jumlah", "subtotal"
            }
        ));
        tbl1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbl1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane11.setViewportView(tbl1);
        if (tbl1.getColumnModel().getColumnCount() > 0) {
            tbl1.getColumnModel().getColumn(0).setMinWidth(150);
            tbl1.getColumnModel().getColumn(0).setMaxWidth(150);
            tbl1.getColumnModel().getColumn(1).setMinWidth(80);
            tbl1.getColumnModel().getColumn(1).setMaxWidth(80);
            tbl1.getColumnModel().getColumn(2).setMinWidth(80);
            tbl1.getColumnModel().getColumn(2).setMaxWidth(80);
            tbl1.getColumnModel().getColumn(3).setMinWidth(80);
            tbl1.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        payment01.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 102, 389, 272));

        jLabel22.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Total Harga");
        payment01.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 408, -1, -1));

        TotalHarga.setEditable(false);
        TotalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalHargaActionPerformed(evt);
            }
        });
        payment01.add(TotalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 128, -1));

        jLabel23.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Bayar");
        payment01.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, -1, 60));

        Bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BayarActionPerformed(evt);
            }
        });
        payment01.add(Bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 128, -1));

        jLabel24.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Kembalian");
        payment01.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, -1, 60));

        Kembalian.setEditable(false);
        Kembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembalianActionPerformed(evt);
            }
        });
        payment01.add(Kembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 128, -1));

        btnKembalian.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnKembalian.setText("Bayar");
        btnKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembalianActionPerformed(evt);
            }
        });
        payment01.add(btnKembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, -1, -1));

        back2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        back2.setText("Back");
        back2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back2ActionPerformed(evt);
            }
        });
        payment01.add(back2, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 116, -1, -1));

        Meja1.setEditable(false);
        Meja1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Meja1ActionPerformed(evt);
            }
        });
        payment01.add(Meja1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 61, -1));

        Close3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Close3.setText("Close");
        Close3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Close3ActionPerformed(evt);
            }
        });
        payment01.add(Close3, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 167, -1, -1));

        utama.add(payment01, "card2");

        login.setBackground(new java.awt.Color(0, 153, 153));
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username");
        login.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        login.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, -1, -1));

        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });
        login.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 206, -1));

        login1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        login1.setText("Login");
        login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login1ActionPerformed(evt);
            }
        });
        login.add(login1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, -1, -1));

        exit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        login.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, -1, -1));
        login.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 206, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 48)); // NOI18N
        jLabel10.setText("LOGIN");

        jLabel1.setFont(new java.awt.Font("Swis721 Blk BT", 0, 48)); // NOI18N
        jLabel1.setText("CAFE.IN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(226, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(253, 253, 253))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(204, 204, 204))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        login.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 103, 639, 150));

        utama.add(login, "card2");

        history.setBackground(new java.awt.Color(0, 153, 153));
        history.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalSeluruh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalSeluruhActionPerformed(evt);
            }
        });
        history.add(totalSeluruh, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 580, 124, -1));

        tbl2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Daftar Pesanan", "Harga", "Jumlah", "subtotal", "Tanggal"
            }
        ));
        tbl2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbl2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane12.setViewportView(tbl2);
        if (tbl2.getColumnModel().getColumnCount() > 0) {
            tbl2.getColumnModel().getColumn(1).setMinWidth(80);
            tbl2.getColumnModel().getColumn(1).setMaxWidth(80);
            tbl2.getColumnModel().getColumn(2).setMinWidth(80);
            tbl2.getColumnModel().getColumn(2).setMaxWidth(80);
            tbl2.getColumnModel().getColumn(3).setMinWidth(80);
            tbl2.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        history.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 158, 577, 376));

        Reset.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Reset.setText("Back");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        history.add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 580, -1, -1));

        Close1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Close1.setText("Close");
        Close1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Close1ActionPerformed(evt);
            }
        });
        history.add(Close1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 580, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Total");
        history.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, 90, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Total Keseluruhan");
        history.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 79, 428, -1));

        utama.add(history, "card2");

        aplikasi.setBackground(new java.awt.Color(0, 153, 153));
        aplikasi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Jenis Pesanan (Minuman) ");
        aplikasi.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        PesanMakanan.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        PesanMakanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));
        PesanMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesanMakananActionPerformed(evt);
            }
        });
        aplikasi.add(PesanMakanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 177, -1));

        meja04.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        meja04.setText("Meja 04");
        meja04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meja04ActionPerformed(evt);
            }
        });
        aplikasi.add(meja04, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 560, -1, -1));

        meja03.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        meja03.setText("Meja 03");
        meja03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meja03ActionPerformed(evt);
            }
        });
        aplikasi.add(meja03, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 560, -1, -1));

        meja02.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        meja02.setText("Meja 02");
        meja02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meja02ActionPerformed(evt);
            }
        });
        aplikasi.add(meja02, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 560, -1, -1));

        meja01.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        meja01.setText("Meja 01");
        meja01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meja01ActionPerformed(evt);
            }
        });
        aplikasi.add(meja01, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, -1, -1));

        Meja.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Meja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Meja" }));
        Meja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MejaActionPerformed(evt);
            }
        });
        aplikasi.add(Meja, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 93, -1));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Daftar Pesanan", "Harga", "Jumlah", "subtotal"
            }
        ));
        tbl.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane10.setViewportView(tbl);
        if (tbl.getColumnModel().getColumnCount() > 0) {
            tbl.getColumnModel().getColumn(0).setMinWidth(150);
            tbl.getColumnModel().getColumn(0).setMaxWidth(150);
            tbl.getColumnModel().getColumn(1).setMinWidth(80);
            tbl.getColumnModel().getColumn(1).setMaxWidth(80);
            tbl.getColumnModel().getColumn(2).setMinWidth(80);
            tbl.getColumnModel().getColumn(2).setMaxWidth(80);
            tbl.getColumnModel().getColumn(3).setMinWidth(80);
            tbl.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        aplikasi.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 420, 200));

        JumlahMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumlahMakananActionPerformed(evt);
            }
        });
        aplikasi.add(JumlahMakanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 32, -1));

        JumlahMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumlahMinumanActionPerformed(evt);
            }
        });
        aplikasi.add(JumlahMinuman, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 32, -1));

        PesanMinuman.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        PesanMinuman.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));
        PesanMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesanMinumanActionPerformed(evt);
            }
        });
        aplikasi.add(PesanMinuman, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 177, -1));

        TambahMinuman.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        TambahMinuman.setText("Tambah");
        TambahMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahMinumanActionPerformed(evt);
            }
        });
        aplikasi.add(TambahMinuman, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        TambahMakanan.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        TambahMakanan.setText("Tambah");
        TambahMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahMakananActionPerformed(evt);
            }
        });
        aplikasi.add(TambahMakanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        btnMakan.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnMakan.setText("Tambah");
        btnMakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakanActionPerformed(evt);
            }
        });
        aplikasi.add(btnMakan, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));

        jmlMakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlMakanActionPerformed(evt);
            }
        });
        aplikasi.add(jmlMakan, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 32, -1));

        jLabel25.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        aplikasi.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 177, -1, -1));

        Makanan.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Makanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));
        Makanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakananActionPerformed(evt);
            }
        });
        aplikasi.add(Makanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 182, -1));

        meja06.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        meja06.setText("Meja 06");
        meja06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meja06ActionPerformed(evt);
            }
        });
        aplikasi.add(meja06, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 560, -1, -1));

        meja05.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        meja05.setText("Meja 05");
        meja05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meja05ActionPerformed(evt);
            }
        });
        aplikasi.add(meja05, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 560, -1, -1));

        Reset1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Reset1.setText("Reset");
        Reset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset1ActionPerformed(evt);
            }
        });
        aplikasi.add(Reset1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, -1, -1));

        Close2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Close2.setText("Close");
        Close2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Close2ActionPerformed(evt);
            }
        });
        aplikasi.add(Close2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Nomor Meja");
        aplikasi.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 30, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Jenis Pesanan (Makanan ) ");
        aplikasi.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 199, -1));

        jLabel28.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Jenis Pesanan (Cemilan) ");
        aplikasi.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 190, -1));

        utama.add(aplikasi, "card2");

        help.setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jList1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1. Pada aplikasi terdapat fitur [Nomor Meja] yang akan digunakan ", "pelayan untuk menanyakan nomor meja dari para pelanggan.", "2. Fitur [Jenis Pesanan] ada 3, yaitu Cemilan, Makanan dan ", "Minuman. Nantinya digunakan pelayan untuk menanyakan pesanan ", "dari para pelanggan.", "3. Setelah melakukan pemesanan, pesanan akan dicetak pada ", "tabel keterangan yang berisi daftar pesanan, jumlah, harga, dan sub total.", "4. Jika pelanggan hendak melakukan pembayaran, maka pelayan ", "akan memencet fitur [Nama Meja] yang terdiri dari 6 buah, yaitu ", "[Meja01], [Meja02], [Meja03], [Meja04], [Meja05], [Meja06]. ", "Untuk itu pelayan akan memilih salah satu dari fitur tersebut sesuai ", "nomor meja pelanggan.", "5. Setelah dipencet salah satu fitur tadi, akan muncul frame baru ", "yang menampilkan keterangan tentang daftar pesanan, harga, jumlah, ", "sub total, total harga, bayar, dan kembalian. Dan pelanggan bisa ", "langsung membayar kepada pelayan.", " ", "\t\t\t\tTerima Kasih" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jList1);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cara Penggunaan Aplikasi");

        javax.swing.GroupLayout helpLayout = new javax.swing.GroupLayout(help);
        help.setLayout(helpLayout);
        helpLayout.setHorizontalGroup(
            helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helpLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, helpLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
            .addGroup(helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(helpLayout.createSequentialGroup()
                    .addGap(232, 639, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        helpLayout.setVerticalGroup(
            helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helpLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel8)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButton5)
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(helpLayout.createSequentialGroup()
                    .addGap(0, 118, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 540, Short.MAX_VALUE)))
        );

        utama.add(help, "card2");

        about.setBackground(new java.awt.Color(0, 153, 153));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 45)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ANGGOTA KELOMPOK");

        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText("M. Ainurrofiq Anwar Buhang\n21051204052\n\nFajar Hindi Saputra\n21051204050\n\nAzhar Daryl Ravysa\n21051204038");
        jScrollPane3.setViewportView(jTextArea3);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout aboutLayout = new javax.swing.GroupLayout(about);
        about.setLayout(aboutLayout);
        aboutLayout.setHorizontalGroup(
            aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutLayout.createSequentialGroup()
                .addGroup(aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aboutLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(aboutLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(aboutLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel7)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        aboutLayout.setVerticalGroup(
            aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton3)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        utama.add(about, "card2");

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setText("File");

        aboutt.setText("About");
        aboutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abouttActionPerformed(evt);
            }
        });
        jMenu1.add(aboutt);

        helpp.setText("Help");
        helpp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helppActionPerformed(evt);
            }
        });
        jMenu1.add(helpp);

        loginn.setText("Login");
        loginn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginnActionPerformed(evt);
            }
        });
        jMenu1.add(loginn);

        logoutt.setText("Logout");
        logoutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logouttActionPerformed(evt);
            }
        });
        jMenu1.add(logoutt);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        aplikasii.setText("Aplikasi");
        aplikasii.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplikasiiActionPerformed(evt);
            }
        });
        jMenu2.add(aplikasii);

        historyy.setText("History");
        historyy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyyActionPerformed(evt);
            }
        });
        jMenu2.add(historyy);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(utama, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        utama.removeAll();
        utama.repaint();
        utama.revalidate();

        utama.add(home);
        utama.repaint();
        utama.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void PesanMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesanMakananActionPerformed

        if (PesanMakanan.getSelectedItem() == "Tahu Goreng") {
            hp = 10000;
        } else if (PesanMakanan.getSelectedItem() == "Kentang Goreng") {
            hp = 15000;
        } else if (PesanMakanan.getSelectedItem() == "Roti Bakar") {
            hp = 25000;
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_PesanMakananActionPerformed

    private void PesanMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesanMinumanActionPerformed
        if (PesanMinuman.getSelectedItem() == "Jus Mangga") {
            hp = 17000;
        } else if (PesanMinuman.getSelectedItem() == "Jus Jambu") {
            hp = 17000;
        } else if (PesanMinuman.getSelectedItem() == "Jus Alpukat") {
            hp = 17000;
        } else if (PesanMinuman.getSelectedItem() == "Red Velvet") {
            hp = 20000;
        } else if (PesanMinuman.getSelectedItem() == "Charcoal") {
            hp = 16000;
        } else if (PesanMinuman.getSelectedItem() == "Chapuchino") {
            hp = 25000;
        } else if (PesanMinuman.getSelectedItem() == "Americano") {
            hp = 25000;
        } else if (PesanMinuman.getSelectedItem() == "Arabica") {
            hp = 25000;
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_PesanMinumanActionPerformed

    private void JumlahMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumlahMinumanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JumlahMinumanActionPerformed

    private void JumlahMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumlahMakananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JumlahMakananActionPerformed

    private void tblAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblAncestorAdded

        // TODO add your handling code here:
    }//GEN-LAST:event_tblAncestorAdded

    private void MejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MejaActionPerformed
        int i;
        if (Meja.getSelectedItem().toString().equals("Meja 01")) {
            for (i = 0; i < 10; i++) {
                tbl.setValueAt(kr[0][i][0], i, 0);
                tbl.setValueAt(kr[0][i][1], i, 1);
                tbl.setValueAt(kr[0][i][2], i, 2);
                tbl.setValueAt(kr[0][i][3], i, 3);
            }
        } else if (Meja.getSelectedItem() == "Meja 02") {
            for (i = 0; i < 10; i++) {
                tbl.setValueAt(kr[1][i][0], i, 0);
                tbl.setValueAt(kr[1][i][1], i, 1);
                tbl.setValueAt(kr[1][i][2], i, 2);
                tbl.setValueAt(kr[1][i][3], i, 3);
            }
        } else if (Meja.getSelectedItem() == "Meja 03") {
            for (i = 0; i < 10; i++) {
                tbl.setValueAt(kr[2][i][0], i, 0);
                tbl.setValueAt(kr[2][i][1], i, 1);
                tbl.setValueAt(kr[2][i][2], i, 2);
                tbl.setValueAt(kr[2][i][3], i, 3);
            }
        } else if (Meja.getSelectedItem() == "Meja 04") {
            for (i = 0; i < 10; i++) {
                tbl.setValueAt(kr[3][i][0], i, 0);
                tbl.setValueAt(kr[3][i][1], i, 1);
                tbl.setValueAt(kr[3][i][2], i, 2);
                tbl.setValueAt(kr[3][i][3], i, 3);
            }
        } else if (Meja.getSelectedItem() == "Meja 05") {
            for (i = 0; i < 10; i++) {
                tbl.setValueAt(kr[4][i][0], i, 0);
                tbl.setValueAt(kr[4][i][1], i, 1);
                tbl.setValueAt(kr[4][i][2], i, 2);
                tbl.setValueAt(kr[4][i][3], i, 3);
            }
        } else if (Meja.getSelectedItem() == "Meja 06") {
            for (i = 0; i < 10; i++) {
                tbl.setValueAt(kr[5][i][0], i, 0);
                tbl.setValueAt(kr[5][i][1], i, 1);
                tbl.setValueAt(kr[5][i][2], i, 2);
                tbl.setValueAt(kr[5][i][3], i, 3);
            }
        }

        //int i;
        //for (i = 0; i < tbl.getRowCount(); i++) {
        //    tbl.setValueAt("", i, 0);
        //    tbl.setValueAt("", i, 1);
        //    tbl.setValueAt("", i, 2);
        //    tbl.setValueAt("", i, 3);
        //    tbl1.setValueAt("", i, 0);
        //    tbl1.setValueAt("", i, 1);
        //    tbl1.setValueAt("", i, 2);
        //    tbl1.setValueAt("", i, 3);
        //}
        JumlahMakanan.setText("");
        JumlahMinuman.setText("");
        jmlMakan.setText("");
        PesanMakanan.setSelectedIndex(0);
        Makanan.setSelectedIndex(0);
        PesanMinuman.setSelectedIndex(0);

        //x = 0;
        // TODO add your handling code here:
    }//GEN-LAST:event_MejaActionPerformed

    private void TambahMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahMinumanActionPerformed

        int p = 0;
        int h = Integer.parseInt(JumlahMinuman.getText()) * hp;
        total += Integer.parseInt(JumlahMinuman.getText()) * hp;
        TotalHarga.setText("Rp. " + total);
        totalSeluruh.setText("Rp. " + total);
        if (Meja.getSelectedItem() == "Meja 01") {
            kr[0][x[0]][0] = PesanMinuman.getSelectedItem() + "";
            kr[0][x[0]][1] = hp + "";
            kr[0][x[0]][2] = JumlahMinuman.getText();
            kr[0][x[0]][3] = h + "";
            p = 0;
        } else if (Meja.getSelectedItem() == "Meja 02") {
            kr[1][x[1]][0] = PesanMinuman.getSelectedItem() + "";
            kr[1][x[1]][1] = hp + "";
            kr[1][x[1]][2] = JumlahMinuman.getText();
            kr[1][x[1]][3] = h + "";
            p = 1;
        } else if (Meja.getSelectedItem() == "Meja 03") {
            kr[2][x[2]][0] = PesanMinuman.getSelectedItem() + "";
            kr[2][x[2]][1] = hp + "";
            kr[2][x[2]][2] = JumlahMinuman.getText();
            kr[2][x[2]][3] = h + "";
            p = 2;
        } else if (Meja.getSelectedItem() == "Meja 04") {
            kr[3][x[3]][0] = PesanMinuman.getSelectedItem() + "";
            kr[3][x[3]][1] = hp + "";
            kr[3][x[3]][2] = JumlahMinuman.getText();
            kr[3][x[3]][3] = h + "";
            p = 3;
        } else if (Meja.getSelectedItem() == "Meja 05") {
            kr[4][x[4]][0] = PesanMinuman.getSelectedItem() + "";
            kr[4][x[4]][1] = hp + "";
            kr[4][x[4]][2] = JumlahMinuman.getText();
            kr[4][x[4]][3] = h + "";
            p = 4;
        } else if (Meja.getSelectedItem() == "Meja 06") {
            kr[5][x[5]][0] = PesanMinuman.getSelectedItem() + "";
            kr[5][x[5]][1] = hp + "";
            kr[5][x[5]][2] = JumlahMinuman.getText();
            kr[5][x[5]][3] = h + "";
            p = 5;
        }
        tbl.setValueAt(PesanMinuman.getSelectedItem(), x[p], 0);
        tbl.setValueAt(hp, x[p], 1);
        tbl.setValueAt(JumlahMinuman.getText(), x[p], 2);
        tbl.setValueAt(h, x[p], 3);
        tbl2.setValueAt(PesanMinuman.getSelectedItem(), hs, 0);
        tbl2.setValueAt(hp, hs, 1);
        tbl2.setValueAt(JumlahMinuman.getText(), hs, 2);
        tbl2.setValueAt(h, hs, 3);
        tbl2.setValueAt(timeStamp, hs, 4);
        hs = hs+1;
        
        x[p] = x[p] + 1;
        // TODO add your handling code here:
    }//GEN-LAST:event_TambahMinumanActionPerformed

    private void TambahMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahMakananActionPerformed
        int p = 0;
        int h = Integer.parseInt(JumlahMakanan.getText()) * hp;
        total += Integer.parseInt(JumlahMakanan.getText()) * hp;
        TotalHarga.setText("Rp. " + total);
        totalSeluruh.setText("Rp. " + total);
        if (Meja.getSelectedItem() == "Meja 01") {
            kr[0][x[0]][0] = PesanMakanan.getSelectedItem() + "";
            kr[0][x[0]][1] = hp + "";
            kr[0][x[0]][2] = JumlahMakanan.getText();
            kr[0][x[0]][3] = h + "";
            p = 0;
        } else if (Meja.getSelectedItem() == "Meja 02") {
            kr[1][x[1]][0] = PesanMakanan.getSelectedItem() + "";
            kr[1][x[1]][1] = hp + "";
            kr[1][x[1]][2] = JumlahMakanan.getText();
            kr[1][x[1]][3] = h + "";
            p = 1;
        } else if (Meja.getSelectedItem() == "Meja 03") {
            kr[2][x[2]][0] = PesanMakanan.getSelectedItem() + "";
            kr[2][x[2]][1] = hp + "";
            kr[2][x[2]][2] = JumlahMakanan.getText();
            kr[2][x[2]][3] = h + "";
            p = 2;
        } else if (Meja.getSelectedItem() == "Meja 04") {
            kr[3][x[3]][0] = PesanMakanan.getSelectedItem() + "";
            kr[3][x[3]][1] = hp + "";
            kr[3][x[3]][2] = JumlahMakanan.getText();
            kr[3][x[3]][3] = h + "";
            p = 3;
        } else if (Meja.getSelectedItem() == "Meja 05") {
            kr[4][x[4]][0] = PesanMinuman.getSelectedItem() + "";
            kr[4][x[4]][1] = hp + "";
            kr[4][x[4]][2] = JumlahMinuman.getText();
            kr[4][x[4]][3] = h + "";
            p = 4;
        } else if (Meja.getSelectedItem() == "Meja 06") {
            kr[5][x[5]][0] = PesanMinuman.getSelectedItem() + "";
            kr[5][x[5]][1] = hp + "";
            kr[5][x[5]][2] = JumlahMinuman.getText();
            kr[5][x[5]][3] = h + "";
            p = 5;
        }
        tbl.setValueAt(PesanMakanan.getSelectedItem(), x[p], 0);
        tbl.setValueAt(hp, x[p], 1);
        tbl.setValueAt(JumlahMakanan.getText(), x[p], 2);
        tbl.setValueAt(h, x[p], 3);
        tbl2.setValueAt(PesanMakanan.getSelectedItem(), hs, 0);
        tbl2.setValueAt(hp, hs, 1);
        tbl2.setValueAt(JumlahMakanan.getText(), hs, 2);
        tbl2.setValueAt(h, hs, 3);
        tbl2.setValueAt(timeStamp, hs, 4);
        hs = hs+1;
        x[p] = x[p] + 1;

        // TODO add your handling code here:

    }//GEN-LAST:event_TambahMakananActionPerformed

    private void tbl1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbl1AncestorAdded

        // TODO add your handling code here:
    }//GEN-LAST:event_tbl1AncestorAdded

    private void TotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalHargaActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_TotalHargaActionPerformed

    private void BayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BayarActionPerformed

    private void KembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembalianActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_KembalianActionPerformed

    private void btnKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembalianActionPerformed
        totalSemua = Integer.parseInt(Bayar.getText()) - total;

        if (totalSemua < 0) {
            JOptionPane.showMessageDialog(this, "Pembayaran Anda Kurang", "PAYMENT", JOptionPane.WARNING_MESSAGE);
        } else if (totalSemua > 0) {
            int pilih = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Tidak Ada Tambahan Pesanan ?", "PAYMENT", JOptionPane.YES_NO_OPTION);
            if (pilih == JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(this, "Pembayaran Anda Berhasil", "PAYMENT", JOptionPane.INFORMATION_MESSAGE);
                totalSemua = Integer.parseInt(Bayar.getText()) - total;

                Kembalian.setText("RP. " + totalSemua);
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnKembalianActionPerformed

    private void tbl2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbl2AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl2AncestorAdded

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        utama.removeAll();
        utama.repaint();
        utama.revalidate();

        utama.add(home);
        utama.repaint();
        utama.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login1ActionPerformed
        if (Username.getText().equals("admin")) {
            if (password.getText().equals("admin")) {
                // Bila Login Sukses Maka Masuk Menu Utama
                utama.removeAll();
                utama.repaint();
                utama.revalidate();

                utama.add(home);
                utama.repaint();
                utama.revalidate();
            } else {
                // Bila Login Gagal Maka Ulangi Login
                JOptionPane.showMessageDialog(this, "<ERROR> Password Salah, Silahkan Coba Lagi", "WARNING", JOptionPane.ERROR_MESSAGE);
                Username.setText("");
                password.setText("");
                Username.requestFocus();

            }

            aplikasii.setVisible(true);
            historyy.setVisible(true);
            logoutt.setVisible(true);
            loginn.setVisible(false);
            BtnLogin.setVisible(false);
        } else if (Username.getText().equals("pelayan")) {
            if (password.getText().equals("pelayan")) {
                // Bila Login Sukses Maka Masuk Menu Utama
                utama.removeAll();
                utama.repaint();
                utama.revalidate();

                utama.add(home);
                utama.repaint();
                utama.revalidate();

                aplikasii.setVisible(true);
                historyy.setVisible(true);
                logoutt.setVisible(true);
                loginn.setVisible(false);
                jLabel23.setVisible(false);
                jLabel24.setVisible(false);
                Bayar.setVisible(false);
                Kembalian.setVisible(false);
                btnKembalian.setVisible(false);
                BtnLogin.setVisible(false);

            } else {
                // Bila Login Gagal Maka Ulangi Login
                JOptionPane.showMessageDialog(this, "<ERROR> Password Salah, Silahkan Coba Lagi", "WARNING", JOptionPane.ERROR_MESSAGE);
                Username.setText("");
                password.setText("");
                Username.requestFocus();

            }
        } else {
            JOptionPane.showMessageDialog(this, "<ERROR> Username Salah, Silahkan Coba Lagi", "WARNING", JOptionPane.ERROR_MESSAGE);
            Username.setText("");
            password.setText("");
            Username.requestFocus();

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_login1ActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        utama.removeAll();
        utama.repaint();
        utama.revalidate();

        utama.add(aplikasi);
        utama.repaint();
        utama.revalidate();
//        JumlahMakanan.setText("");
//        JumlahMinuman.setText("");
//        jmlMakan.setText("");
//        TotalHarga.setText("");
//        Bayar.setText("");
//        Kembalian.setText("");
//        int p = 0;
//        int i;
//        for (i = 0; i < tbl.getRowCount(); i++) {
//            tbl.setValueAt("", i, 0);
//            tbl.setValueAt("", i, 1);
//            tbl.setValueAt("", i, 2);
//            tbl.setValueAt("", i, 3);
//        }
//        PesanMakanan.setSelectedIndex(0);
//        PesanMinuman.setSelectedIndex(0);
//        Makanan.setSelectedIndex(0);
//        if (Meja.getSelectedItem() == "Meja 01") {
//            p = 0;
//        } else if (Meja.getSelectedItem() == "Meja 02") {
//            p = 1;
//        } else if (Meja.getSelectedItem() == "Meja 03") {
//            p = 2;
//        } else if (Meja.getSelectedItem() == "Meja 04") {
//            p = 3;
//        } else if (Meja.getSelectedItem() == "Meja 05") {
//            p = 4;
//        } else if (Meja.getSelectedItem() == "Meja 06") {
//            p = 5;
//        }
//        x[p] = 0;
//        // TODO add your handling code here:
    }//GEN-LAST:event_ResetActionPerformed

    private void Close1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Close1ActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_Close1ActionPerformed

    private void Reset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset1ActionPerformed

        JumlahMakanan.setText("");
        JumlahMinuman.setText("");
        jmlMakan.setText("");
        TotalHarga.setText("");
        Bayar.setText("");
        Kembalian.setText("");
        int p = 0;
        int i;
        for (i = 0; i < tbl.getRowCount(); i++) {
            tbl.setValueAt("", i, 0);
            tbl.setValueAt("", i, 1);
            tbl.setValueAt("", i, 2);
            tbl.setValueAt("", i, 3);
        }
        PesanMakanan.setSelectedIndex(0);
        PesanMinuman.setSelectedIndex(0);
        Makanan.setSelectedIndex(0);
        Meja.setSelectedIndex(0);
        if (Meja.getSelectedItem() == "Meja 01") {
            p = 0;
        } else if (Meja.getSelectedItem() == "Meja 02") {
            p = 1;
        } else if (Meja.getSelectedItem() == "Meja 03") {
            p = 2;
        } else if (Meja.getSelectedItem() == "Meja 04") {
            p = 3;
        } else if (Meja.getSelectedItem() == "Meja 05") {
            p = 4;
        } else if (Meja.getSelectedItem() == "Meja 06") {
            p = 5;
        }
        x[p] = 0;
        // TODO add your handling code here:
    }//GEN-LAST:event_Reset1ActionPerformed

    private void Close2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Close2ActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_Close2ActionPerformed

    private void Meja1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Meja1ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_Meja1ActionPerformed

    private void meja01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meja01ActionPerformed
        Meja1.setText("Meja 01");
        int i;
        for (i = 0; i <= 14; i++) {
            tbl1.setValueAt("", i, 0);
            tbl1.setValueAt("", i, 1);
            tbl1.setValueAt("", i, 2);
            tbl1.setValueAt("", i, 3);
        }
        int har = 0;
        utama.removeAll();
        utama.repaint();
        utama.revalidate();

        utama.add(payment01);
        utama.repaint();
        utama.revalidate();
        
        for (i = 0; i < x[0]; i++) {
            tbl1.setValueAt(kr[0][i][0], i, 0);
            tbl1.setValueAt(kr[0][i][1], i, 1);
            tbl1.setValueAt(kr[0][i][2], i, 2);
            tbl1.setValueAt(kr[0][i][3], i, 3);
            har = har + Integer.parseInt(kr[0][i][3]);
        }
        TotalHarga.setText(har+"");
        // TODO add your handling code here:
    }//GEN-LAST:event_meja01ActionPerformed

    private void back2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back2ActionPerformed
        utama.removeAll();
        utama.repaint();
        utama.revalidate();

        utama.add(aplikasi);
        utama.repaint();
        utama.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_back2ActionPerformed

    private void meja02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meja02ActionPerformed
        Meja1.setText("Meja 02");
        int i;
        for (i = 0; i <= 14; i++) {
            tbl1.setValueAt("", i, 0);
            tbl1.setValueAt("", i, 1);
            tbl1.setValueAt("", i, 2);
            tbl1.setValueAt("", i, 3);
        }
        utama.removeAll();
        utama.repaint();
        utama.revalidate();

        utama.add(payment01);
        utama.repaint();
        utama.revalidate();
        int har=0;
        for (i = 0; i < x[1]; i++) {
            tbl1.setValueAt(kr[1][i][0], i, 0);
            tbl1.setValueAt(kr[1][i][1], i, 1);
            tbl1.setValueAt(kr[1][i][2], i, 2);
            tbl1.setValueAt(kr[1][i][3], i, 3);
            har = har + Integer.parseInt(kr[1][i][3]);
        }
        
        TotalHarga.setText(har+"");
        // TODO add your handling code here:
    }//GEN-LAST:event_meja02ActionPerformed

    private void meja03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meja03ActionPerformed
        Meja1.setText("Meja 03");
        int i;
        for (i = 0; i <= 14; i++) {
            tbl1.setValueAt("", i, 0);
            tbl1.setValueAt("", i, 1);
            tbl1.setValueAt("", i, 2);
            tbl1.setValueAt("", i, 3);
        }
        utama.removeAll();
        utama.repaint();
        utama.revalidate();

        utama.add(payment01);
        utama.repaint();
        utama.revalidate();
        int har=0;
        
        for (i = 0; i < x[2]; i++) {
            tbl1.setValueAt(kr[2][i][0], i, 0);
            tbl1.setValueAt(kr[2][i][1], i, 1);
            tbl1.setValueAt(kr[2][i][2], i, 2);
            tbl1.setValueAt(kr[2][i][3], i, 3);
            har = har + Integer.parseInt(kr[2][i][3]);
        }
        TotalHarga.setText(har+"");
        // TODO add your handling code here:
    }//GEN-LAST:event_meja03ActionPerformed

    private void meja04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meja04ActionPerformed
        Meja1.setText("Meja 04");
        int i;
        for (i = 0; i <= 14; i++) {
            tbl1.setValueAt("", i, 0);
            tbl1.setValueAt("", i, 1);
            tbl1.setValueAt("", i, 2);
            tbl1.setValueAt("", i, 3);
        }
        utama.removeAll();
        utama.repaint();
        utama.revalidate();

        utama.add(payment01);
        utama.repaint();
        utama.revalidate();
        int har=0;
        
        for (i = 0; i < x[3]; i++) {
            tbl1.setValueAt(kr[3][i][0], i, 0);
            tbl1.setValueAt(kr[3][i][1], i, 1);
            tbl1.setValueAt(kr[3][i][2], i, 2);
            tbl1.setValueAt(kr[3][i][3], i, 3);
            har = har + Integer.parseInt(kr[3][i][3]);
        }
        TotalHarga.setText(har+"");
        // TODO add your handling code here:
    }//GEN-LAST:event_meja04ActionPerformed

    private void meja05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meja05ActionPerformed
        Meja1.setText("Meja 05");
        int i;
        for (i = 0; i <= 14; i++) {
            tbl1.setValueAt("", i, 0);
            tbl1.setValueAt("", i, 1);
            tbl1.setValueAt("", i, 2);
            tbl1.setValueAt("", i, 3);
        }
        utama.removeAll();
        utama.repaint();
        utama.revalidate();

        utama.add(payment01);
        utama.repaint();
        utama.revalidate();
        int har=0;
        
        for (i = 0; i < x[4]; i++) {
            tbl1.setValueAt(kr[4][i][0], i, 0);
            tbl1.setValueAt(kr[4][i][1], i, 1);
            tbl1.setValueAt(kr[4][i][2], i, 2);
            tbl1.setValueAt(kr[4][i][3], i, 3);
            har = har + Integer.parseInt(kr[4][i][3]);
        }
        TotalHarga.setText(har+"");
        // TODO add your handling code here:
    }//GEN-LAST:event_meja05ActionPerformed

    private void meja06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meja06ActionPerformed
        Meja1.setText("Meja 06");
        int i;
        for (i = 0; i <= 14; i++) {
            tbl1.setValueAt("", i, 0);
            tbl1.setValueAt("", i, 1);
            tbl1.setValueAt("", i, 2);
            tbl1.setValueAt("", i, 3);
        }
        utama.removeAll();
        utama.repaint();
        utama.revalidate();

        utama.add(payment01);
        utama.repaint();
        utama.revalidate();
        int har=0;
        for (i = 0; i < x[5]; i++) {
            tbl1.setValueAt(kr[5][i][0], i, 0);
            tbl1.setValueAt(kr[5][i][1], i, 1);
            tbl1.setValueAt(kr[5][i][2], i, 2);
            tbl1.setValueAt(kr[5][i][3], i, 3);
            har = har + Integer.parseInt(kr[5][i][3]);
        }
        TotalHarga.setText(har+"");
        // TODO add your handling code here:
    }//GEN-LAST:event_meja06ActionPerformed

    private void Close3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Close3ActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_Close3ActionPerformed

    private void MakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakananActionPerformed
        if (Makanan.getSelectedItem() == "Nasi Goreng") {
            hp = 25000;
        } else if (Makanan.getSelectedItem() == "Mie Goreng") {
            hp = 25000;
        } else if (Makanan.getSelectedItem() == "Crispy Chiken") {
            hp = 18000;
        } else if (Makanan.getSelectedItem() == "Hamburger") {
            hp = 15000;
        } else if (Makanan.getSelectedItem() == "Pasta") {
            hp = 28000;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_MakananActionPerformed

    private void jmlMakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlMakanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlMakanActionPerformed

    private void btnMakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakanActionPerformed

        int p = 0;
        int h = Integer.parseInt(jmlMakan.getText()) * hp;
        total += Integer.parseInt(jmlMakan.getText()) * hp;
        TotalHarga.setText("Rp. " + total);
        totalSeluruh.setText("Rp. " + total);
        if (Meja.getSelectedItem() == "Meja 01") {
            kr[0][x[0]][0] = Makanan.getSelectedItem() + "";
            kr[0][x[0]][1] = hp + "";
            kr[0][x[0]][2] = jmlMakan.getText();
            kr[0][x[0]][3] = h + "";
            p = 0;
        } else if (Meja.getSelectedItem() == "Meja 02") {
            kr[1][x[1]][0] = Makanan.getSelectedItem() + "";
            kr[1][x[1]][1] = hp + "";
            kr[1][x[1]][2] = jmlMakan.getText();
            kr[1][x[1]][3] = h + "";
            p = 1;
        } else if (Meja.getSelectedItem() == "Meja 03") {
            kr[2][x[2]][0] = Makanan.getSelectedItem() + "";
            kr[2][x[2]][1] = hp + "";
            kr[2][x[2]][2] = jmlMakan.getText();
            kr[2][x[2]][3] = h + "";
            p = 2;
        } else if (Meja.getSelectedItem() == "Meja 04") {
            kr[3][x[3]][0] = Makanan.getSelectedItem() + "";
            kr[3][x[3]][1] = hp + "";
            kr[3][x[3]][2] = jmlMakan.getText();
            kr[3][x[3]][3] = h + "";
            p = 3;
        } else if (Meja.getSelectedItem() == "Meja 05") {
            kr[4][x[4]][0] = Makanan.getSelectedItem() + "";
            kr[4][x[4]][1] = hp + "";
            kr[4][x[4]][2] = jmlMakan.getText();
            kr[4][x[4]][3] = h + "";
            p = 4;
        } else if (Meja.getSelectedItem() == "Meja 06") {
            kr[5][x[5]][0] = Makanan.getSelectedItem() + "";
            kr[5][x[5]][1] = hp + "";
            kr[5][x[5]][2] = jmlMakan.getText();
            kr[5][x[5]][3] = h + "";
            p = 5;
        }
        tbl.setValueAt(Makanan.getSelectedItem(), x[p], 0);
        tbl.setValueAt(hp, x[p], 1);
        tbl.setValueAt(jmlMakan.getText(), x[p], 2);
        tbl.setValueAt(h, x[p], 3);
        tbl2.setValueAt(Makanan.getSelectedItem(), hs, 0);
        tbl2.setValueAt(hp, hs, 1);
        tbl2.setValueAt(jmlMakan.getText(), hs, 2);
        tbl2.setValueAt(h, hs, 3);
        tbl2.setValueAt(timeStamp, hs, 4);
        hs = hs+1;
        x[p] = x[p] + 1;
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMakanActionPerformed

    private void helppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helppActionPerformed
        utama.removeAll();
        utama.repaint();
        utama.revalidate();

        utama.add(help);
        utama.repaint();
        utama.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_helppActionPerformed

    private void abouttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abouttActionPerformed
        utama.removeAll();
        utama.repaint();
        utama.revalidate();

        utama.add(about);
        utama.repaint();
        utama.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_abouttActionPerformed

    private void loginnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginnActionPerformed
        utama.removeAll();
        utama.repaint();
        utama.revalidate();

        utama.add(login);
        utama.repaint();
        utama.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_loginnActionPerformed

    private void logouttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logouttActionPerformed
        int pilih = JOptionPane.showConfirmDialog(null, "Yakin Keluar?", "KELUAR", JOptionPane.YES_NO_OPTION);
        if (pilih == JOptionPane.YES_OPTION) {

            utama.removeAll();
            utama.repaint();
            utama.revalidate();

            utama.add(login);
            utama.repaint();
            utama.revalidate();
            Username.setText("");
            password.setText("");
            jLabel23.setVisible(true);
            jLabel24.setVisible(true);
            Bayar.setVisible(true);
            Kembalian.setVisible(true);
            btnKembalian.setVisible(true);
            aplikasii.setVisible(false);
            historyy.setVisible(false);
            BtnLogin.setVisible(true);
            logoutt.setVisible(false);
            loginn.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_logouttActionPerformed

    private void BtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginActionPerformed
        utama.removeAll();
        utama.repaint();
        utama.revalidate();

        utama.add(login);
        utama.repaint();
        utama.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnLoginActionPerformed

    private void aplikasiiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplikasiiActionPerformed
        utama.removeAll();
        utama.repaint();
        utama.revalidate();

        utama.add(aplikasi);
        utama.repaint();
        utama.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_aplikasiiActionPerformed

    private void historyyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyyActionPerformed
        utama.removeAll();
        utama.repaint();
        utama.revalidate();

        utama.add(history);
        utama.repaint();
        utama.revalidate();

        // TODO add your handling code here:
    }//GEN-LAST:event_historyyActionPerformed

    private void totalSeluruhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalSeluruhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalSeluruhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UASSSS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UASSSS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UASSSS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UASSSS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UASSSS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bayar;
    private javax.swing.JButton BtnLogin;
    private javax.swing.JButton Close1;
    private javax.swing.JButton Close2;
    private javax.swing.JButton Close3;
    private javax.swing.JTextField JumlahMakanan;
    private javax.swing.JTextField JumlahMinuman;
    private javax.swing.JTextField Kembalian;
    private javax.swing.JComboBox<String> Makanan;
    private javax.swing.JComboBox<String> Meja;
    private javax.swing.JTextField Meja1;
    private javax.swing.JComboBox<String> PesanMakanan;
    private javax.swing.JComboBox<String> PesanMinuman;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Reset1;
    private javax.swing.JButton TambahMakanan;
    private javax.swing.JButton TambahMinuman;
    private javax.swing.JTextField TotalHarga;
    private javax.swing.JTextField Username;
    private javax.swing.JPanel about;
    private javax.swing.JMenuItem aboutt;
    private javax.swing.JPanel aplikasi;
    private javax.swing.JMenuItem aplikasii;
    private javax.swing.JButton back2;
    private javax.swing.JButton btnKembalian;
    private javax.swing.JButton btnMakan;
    private javax.swing.JButton exit;
    private javax.swing.JPanel help;
    private javax.swing.JMenuItem helpp;
    private javax.swing.JPanel history;
    private javax.swing.JMenuItem historyy;
    private javax.swing.JPanel home;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jmlMakan;
    private javax.swing.JPanel login;
    private javax.swing.JButton login1;
    private javax.swing.JMenuItem loginn;
    private javax.swing.JMenuItem logoutt;
    private javax.swing.JButton meja01;
    private javax.swing.JButton meja02;
    private javax.swing.JButton meja03;
    private javax.swing.JButton meja04;
    private javax.swing.JButton meja05;
    private javax.swing.JButton meja06;
    private javax.swing.JPasswordField password;
    private javax.swing.JPanel payment01;
    private javax.swing.JTable tbl;
    private javax.swing.JTable tbl1;
    private javax.swing.JTable tbl2;
    private javax.swing.JTextField totalSeluruh;
    private javax.swing.JPanel utama;
    // End of variables declaration//GEN-END:variables
}
